import {
  BRIDGE_CASING_COLOR,
  KIDBUS_DAY_STYLE,
  ROAD_CASING_COLOR_MAJOR,
  ROAD_CASING_COLOR_NARROW,
  ROAD_FILL_COLOR_MAJOR,
  ROAD_FILL_COLOR_NARROW,
  TUNNEL_CASING_COLOR,
  type KidbusDayStyle,
  type StyleExpression,
} from './kidbus-day';

/**
 * Night road fills, class by class: the day hierarchy (arterials amber, minor
 * roads grey) with the amber muted and the greys cooled so a dark map does not
 * glow. Same match shape as the day style, so the two can be diffed by eye.
 */
const NIGHT_SURFACE_CASING_COLOR: StyleExpression = [
  'match',
  ['get', 'class'],
  ['motorway', 'motorway_link', 'trunk', 'trunk_link', 'primary', 'primary_link'],
  '#5f4f1f',
  '#1a1b1d',
];

const NIGHT_FILL_COLOR: StyleExpression = [
  'match',
  ['get', 'class'],
  ['motorway', 'motorway_link', 'trunk', 'trunk_link'],
  '#a8862f',
  ['primary', 'primary_link'],
  '#9a7a2a',
  ['secondary', 'secondary_link', 'tertiary', 'tertiary_link'],
  '#7d6526',
  '#3c4043',
];

/**
 * KidBus night cartography — the KidBus day style under a dark
 * (Google-night-like) palette.
 *
 * ### What changes and what does not
 *
 * ONLY paint. Sources (the one OpenFreeMap/OpenMapTiles vector source), the
 * sprite (our own `/map-sprites/kidbus`, generated by
 * `scripts/generate-kidbus-sprite.mjs`) and the glyphs (OpenFreeMap font host)
 * are carried over **by reference from the day style** — same free tiles, same
 * keyless URLs, same CSP; the night variant adds no provider, no second tile
 * host and no network surface a daytime session did not already have. Layout
 * (fonts, sizes, placement, minzooms, icon images, sort keys) is untouched: the
 * night map's labels and icons are the day map's labels and icons, and a spec
 * asserts that field by field.
 *
 * ### The palette, and why it is keyed by layer id
 *
 * The day style is the structural source of truth: every layer the day style
 * draws has an entry here, or it would render in daylight colours on a black
 * map. The map below therefore names **all** of its layers — land, water,
 * buildings, the three road passes (tunnel / surface / bridge), rail,
 * boundaries, water names, road names, every `place-*` class and the POIs —
 * so adding a layer to the day style without a night paint is a visible gap in
 * review *and* is caught by `web/src/features/map/style-variant.spec.ts`
 * ("every layer that has a day paint has a night paint").
 *
 * The relationships from the day style survive the recolouring: road fills keep
 * the class hierarchy (arterials stay amber, minor roads stay grey), a tunnel's
 * casing stays lighter than the surface road's, a bridge's stays darker, and
 * label sizes — not colours — keep the place hierarchy (city brightest, then
 * town, village, suburb, quarter, hamlet, neighbourhood).
 */

/** Per-layer night paints, keyed by the day style's layer ids. */
const NIGHT_PAINT: Record<string, Record<string, unknown>> = {
  // Land.
  background: { 'background-color': '#202124' },
  // Vegetation: the day's greens taken down to muted dark tones.
  landcover: {
    'fill-color': ['match', ['get', 'class'], ['park', 'grass'], '#263c3f', ['wood'], '#1f2f22', '#202124'],
  },
  // Land use: the day tints, one notch off the land so an area still reads.
  landuse: {
    'fill-color': [
      'match',
      ['get', 'class'],
      ['park', 'grass', 'garden', 'playground', 'pitch', 'nature_reserve'],
      '#263c3f',
      ['school', 'college', 'university', 'kindergarten', 'education'],
      '#2b2c2f',
      ['hospital', 'clinic', 'doctors'],
      '#332b2e',
      ['cemetery'],
      '#242e26',
      ['commercial', 'retail', 'industrial', 'railway'],
      '#242527',
      '#202124',
    ],
    'fill-opacity': 0.7,
  },
  // Water and waterways: Google's deep night blue.
  water: { 'fill-color': '#17263c' },
  waterway: {
    'line-color': '#17263c',
    'line-width': ['interpolate', ['linear'], ['zoom'], 8, 0.5, 12, 1.2, 16, 3.5, 20, 7],
  },
  // Buildings: a whisper above the land, against the road casing colour.
  building: { 'fill-color': '#2f3134', 'fill-outline-color': '#3c4043' },
  rail: { 'line-color': '#3c4043', 'line-dasharray': [2, 2], 'line-width': ['interpolate', ['linear'], ['zoom'], 10, 0.5, 14, 1, 18, 2.4] },
  // Roads are NOT listed here: `recolourRoad` below swaps their `line-color`
  // by matching the day colour, so a new width group (or a fourth brunnel
  // pass) is recoloured the moment the day style grows it, and the widths
  // themselves are copied verbatim — geometry can never drift at dusk.
  // Boundaries: subordinate at night.
  boundary: {
    'line-color': '#5f6368',
    'line-dasharray': [3, 2],
    'line-width': ['interpolate', ['linear'], ['zoom'], 3, 0.6, 10, 1.1, 16, 1.6],
  },
  // Water names: the day blue, lightened.
  water_name: { 'text-color': '#8ab4f8', 'text-halo-color': '#17263c', 'text-halo-width': 1.2 },
  'water_name-point': { 'text-color': '#8ab4f8', 'text-halo-color': '#17263c', 'text-halo-width': 1.2 },
  // Road names: Google's night label grey over a land-coloured halo.
  transportation_name: {
    'text-color': '#9aa0a6',
    'text-halo-color': '#202124',
    'text-halo-width': 1.6,
    'text-halo-blur': 0.4,
  },
  'transportation_name-minor': {
    'text-color': '#80868b',
    'text-halo-color': '#202124',
    'text-halo-width': 1.3,
    'text-halo-blur': 0.4,
  },
  // Places: the size ladder carries the hierarchy, so the colours only need to
  // step down with it.
  'place-city': { 'text-color': '#e8eaed', 'text-halo-color': '#202124', 'text-halo-width': 2.2, 'text-halo-blur': 0.3 },
  'place-town': { 'text-color': '#dadce0', 'text-halo-color': '#202124', 'text-halo-width': 1.8, 'text-halo-blur': 0.3 },
  'place-village': { 'text-color': '#bdc1c6', 'text-halo-color': '#202124', 'text-halo-width': 1.6 },
  'place-suburb': { 'text-color': '#9aa0a6', 'text-halo-color': '#202124', 'text-halo-width': 1.5 },
  'place-quarter': { 'text-color': '#9aa0a6', 'text-halo-color': '#202124', 'text-halo-width': 1.4 },
  'place-hamlet': { 'text-color': '#90959a', 'text-halo-color': '#202124', 'text-halo-width': 1.3 },
  'place-neighbourhood': { 'text-color': '#80868b', 'text-halo-color': '#202124', 'text-halo-width': 1.2, 'text-halo-blur': 0.3 },
  'place-state': { 'text-color': '#80868b', 'text-halo-color': '#202124', 'text-halo-width': 1.2 },
  // POIs: labels only — the icon colours come from the sprite, which the night
  // style deliberately shares with the day style (one sprite, one download).
  poi: { 'text-color': '#9aa0a6', 'text-halo-color': '#202124', 'text-halo-width': 1.2, 'text-halo-blur': 0.3 },
};

/**
 * The night twin of every road colour the day style can paint with. Keyed by
 * *identity* against the day style's own exported tables, so a road is
 * recoloured because it is that road, not because its id happens to start with
 * `road-`. Fills take the night class palette (arterials stay amber, minor
 * roads stay grey); casings take the night casing palette, and the two flat
 * pass colours keep their day relationship (a tunnel's casing lighter, a
 * bridge's darker than the surface road's).
 */
const NIGHT_LINE_COLOR: ReadonlyArray<readonly [unknown, StyleExpression]> = [
  [ROAD_FILL_COLOR_MAJOR, NIGHT_FILL_COLOR],
  [ROAD_FILL_COLOR_NARROW, NIGHT_FILL_COLOR],
  [ROAD_CASING_COLOR_MAJOR, NIGHT_SURFACE_CASING_COLOR],
  [ROAD_CASING_COLOR_NARROW, NIGHT_SURFACE_CASING_COLOR],
  [TUNNEL_CASING_COLOR, '#26282b'],
  [BRIDGE_CASING_COLOR, '#141516'],
];

/**
 * The night paint for one road layer: its day paint with `line-color` swapped.
 * Returns null when the layer is not a road (its colour is not one of the day
 * road colours), which is how this stays a *rule* rather than an id list.
 */
function recolourRoad(dayPaint: Record<string, unknown>): Record<string, unknown> | null {
  const swap = NIGHT_LINE_COLOR.find(([dayColor]) => dayColor === dayPaint['line-color']);
  if (!swap) return null;
  return { ...dayPaint, 'line-color': swap[1] };
}

/**
 * The night paint for one day layer, or null when the layer keeps its day
 * paint as-is. Colours are overridden; **every other paint key is copied from
 * the day layer** (widths included), so this function can only change what a
 * colour changes.
 *
 * Exported for `style-variant.spec.ts`, which walks the day style and asserts
 * that every painted layer is either recoloured here or deliberately not.
 */
export function nightPaintFor(layer: {
  readonly id: string;
  readonly paint?: Record<string, unknown>;
}): Record<string, unknown> | null {
  const dayPaint = layer.paint;
  if (!dayPaint) return null;
  const overrides = recolourRoad(dayPaint) ?? NIGHT_PAINT[layer.id];
  return overrides ? { ...dayPaint, ...overrides } : null;
}

/**
 * The night style's shape: version/sources/glyphs/sprite are typed as **the
 * day's own fields** (the transform passes them through untouched by
 * reference), while layers are plain layer records — the day style's `as const`
 * literal tuple cannot express paint-overridden layers.
 */
export interface KidbusNightStyle {
  readonly version: KidbusDayStyle['version'];
  readonly name: 'kidbus-night';
  readonly sources: KidbusDayStyle['sources'];
  readonly glyphs: KidbusDayStyle['glyphs'];
  readonly sprite: KidbusDayStyle['sprite'];
  readonly layers: ReadonlyArray<Record<string, unknown>>;
}

/**
 * Builds the night style from the day style. Sources, glyphs and sprite are
 * NOT cloned or replaced — identity is the guarantee that night adds no new
 * network surface, and a spec asserts it.
 */
export function kidbusNightStyle(day: KidbusDayStyle): KidbusNightStyle {
  return {
    version: day.version,
    name: 'kidbus-night',
    sources: day.sources,
    glyphs: day.glyphs,
    sprite: day.sprite,
    layers: day.layers.map((layer) => {
      const paint = nightPaintFor(layer);
      return paint ? { ...layer, paint } : { ...layer };
    }),
  };
}

export const KIDBUS_NIGHT_STYLE = kidbusNightStyle(KIDBUS_DAY_STYLE);
