/**
 * The complete API route table for the end-to-end suites.
 *
 * `src/app/api/v1/**` is Next's routing surface: one directory per path, each
 * re-exporting verb handlers from the endpoint definitions. The e2e tests do
 * not run Next, so the same definitions are mounted here on a plain HTTP
 * server instead — the handlers, guards, validation and envelope under test
 * are identical, only the router differs.
 *
 * Generated from the definitions; keep in sync when adding an endpoint.
 */
import type { TestRoute } from '../../src/server/http/test-server';
import {
  getAdminDashboard,
  getAdminPlans,
  getAdminPlansById,
  getAdminSchools,
  getAdminSchoolsById,
  getAdminSchoolsByIdAdmins,
  getAdminSchoolsBySchoolIdSubscription,
  getAdminSchoolsBySchoolIdSubscriptionHistory,
  getAdminSubscriptions,
  patchAdminPlansById,
  patchAdminSchoolsById,
  patchAdminSchoolsByIdAdminsByAdminId,
  patchAdminSchoolsBySchoolIdSubscription,
  postAdminPlans,
  postAdminPlansByIdActivate,
  postAdminPlansByIdDeactivate,
  postAdminSchools,
  postAdminSchoolsByIdActivate,
  postAdminSchoolsByIdAdmins,
  postAdminSchoolsByIdAdminsByAdminIdActivate,
  postAdminSchoolsByIdAdminsByAdminIdDeactivate,
  postAdminSchoolsByIdAdminsByAdminIdResetpassword,
  postAdminSchoolsByIdDeactivate,
  postAdminSchoolsBySchoolIdSubscription,
  postAdminSchoolsBySchoolIdSubscriptionCancel,
} from '../../src/server/api/admin';
import {
  deleteAdminSchoolsBySchoolIdManageBusesById,
  deleteAdminSchoolsBySchoolIdManageConductorsById,
  deleteAdminSchoolsBySchoolIdManageDriversById,
  deleteAdminSchoolsBySchoolIdManageParentsByParentId,
  deleteAdminSchoolsBySchoolIdManageParentsByParentIdStudentsByStudentId,
  deleteAdminSchoolsBySchoolIdManageRouteassignmentsById,
  deleteAdminSchoolsBySchoolIdManageRoutesById,
  deleteAdminSchoolsBySchoolIdManageStopsById,
  deleteAdminSchoolsBySchoolIdManageStudentsById,
  deleteAdminSchoolsBySchoolIdManageStudentsByStudentIdGuardiansByParentId,
  getAdminSchoolsBySchoolIdManageBuses,
  getAdminSchoolsBySchoolIdManageBusesById,
  getAdminSchoolsBySchoolIdManageConductors,
  getAdminSchoolsBySchoolIdManageConductorsById,
  getAdminSchoolsBySchoolIdManageDrivers,
  getAdminSchoolsBySchoolIdManageDriversById,
  getAdminSchoolsBySchoolIdManageExports,
  getAdminSchoolsBySchoolIdManageExportsByDataset,
  getAdminSchoolsBySchoolIdManageImportsByModuleTemplate,
  getAdminSchoolsBySchoolIdManageImportsHistory,
  getAdminSchoolsBySchoolIdManageImportsHistoryById,
  getAdminSchoolsBySchoolIdManageImportsHistoryByIdErrorfile,
  getAdminSchoolsBySchoolIdManageImportsModules,
  getAdminSchoolsBySchoolIdManageParents,
  getAdminSchoolsBySchoolIdManageParentsByParentId,
  getAdminSchoolsBySchoolIdManageParentsByParentIdStudents,
  getAdminSchoolsBySchoolIdManageReports,
  getAdminSchoolsBySchoolIdManageReportsByReport,
  getAdminSchoolsBySchoolIdManageReportsByReportExport,
  getAdminSchoolsBySchoolIdManageReportsOverview,
  getAdminSchoolsBySchoolIdManageRouteassignments,
  getAdminSchoolsBySchoolIdManageRouteassignmentsById,
  getAdminSchoolsBySchoolIdManageRoutes,
  getAdminSchoolsBySchoolIdManageRoutesById,
  getAdminSchoolsBySchoolIdManageRoutesByIdDetails,
  getAdminSchoolsBySchoolIdManageRoutesByIdStops,
  getAdminSchoolsBySchoolIdManageSessionCurrent,
  getAdminSchoolsBySchoolIdManageStops,
  getAdminSchoolsBySchoolIdManageStopsById,
  getAdminSchoolsBySchoolIdManageStudents,
  getAdminSchoolsBySchoolIdManageStudentsById,
  getAdminSchoolsBySchoolIdManageStudentsByStudentIdGuardians,
  patchAdminSchoolsBySchoolIdManageBusesById,
  patchAdminSchoolsBySchoolIdManageConductorsById,
  patchAdminSchoolsBySchoolIdManageDriversById,
  patchAdminSchoolsBySchoolIdManageParentsByParentId,
  patchAdminSchoolsBySchoolIdManageParentsByParentIdStudentsByStudentId,
  patchAdminSchoolsBySchoolIdManageRouteassignmentsById,
  patchAdminSchoolsBySchoolIdManageRoutesById,
  patchAdminSchoolsBySchoolIdManageStopsById,
  patchAdminSchoolsBySchoolIdManageStudentsById,
  patchAdminSchoolsBySchoolIdManageStudentsByStudentIdGuardiansByParentId,
  postAdminSchoolsBySchoolIdManageBuses,
  postAdminSchoolsBySchoolIdManageConductors,
  postAdminSchoolsBySchoolIdManageDrivers,
  postAdminSchoolsBySchoolIdManageImportsByModuleCommit,
  postAdminSchoolsBySchoolIdManageImportsByModuleValidate,
  postAdminSchoolsBySchoolIdManageParents,
  postAdminSchoolsBySchoolIdManageParentsByParentIdStudents,
  postAdminSchoolsBySchoolIdManageRouteassignments,
  postAdminSchoolsBySchoolIdManageRoutes,
  postAdminSchoolsBySchoolIdManageSession,
  postAdminSchoolsBySchoolIdManageSessionEnd,
  postAdminSchoolsBySchoolIdManageStops,
  postAdminSchoolsBySchoolIdManageStudents,
  postAdminSchoolsBySchoolIdManageStudentsByStudentIdGuardians,
  putAdminSchoolsBySchoolIdManageRoutesByIdStops,
} from '../../src/server/api/admin-manage';
import {
  deleteAssignmentsById,
  deleteRouteassignmentsById,
  getAssignments,
  getAssignmentsById,
  getRouteassignments,
  getRouteassignmentsById,
  patchAssignmentsById,
  patchRouteassignmentsById,
  postAssignments,
  postRouteassignments,
} from '../../src/server/api/assignments';
import {
  getAuditlogs,
} from '../../src/server/api/audit';
import {
  getAuthCsrf,
  postAuthLogin,
  postAuthLogout,
  postAuthRefresh,
} from '../../src/server/api/auth';
import {
  getAuthtestAdminonly,
  getAuthtestMe,
  getAuthtestStaffonly,
} from '../../src/server/api/auth-test';
import {
  deleteBusesById,
  getBuses,
  getBusesById,
  patchBusesById,
  postBuses,
} from '../../src/server/api/buses';
import {
  getExports,
  getExportsByDataset,
} from '../../src/server/api/data-transfer-export';
import {
  getImportsByModuleTemplate,
  getImportsHistory,
  getImportsHistoryById,
  getImportsHistoryByIdErrorfile,
  getImportsModules,
  postImportsByModuleCommit,
  postImportsByModuleValidate,
} from '../../src/server/api/data-transfer-import';
import {
  deleteBusesByBusIdDocumentsById,
  deleteDriversByDriverIdDocumentsById,
  getBusesByBusIdDocuments,
  getBusesByBusIdDocumentsById,
  getBusesByBusIdDocumentsCompliance,
  getDocumentrequirements,
  getDocumentsOverview,
  getDriversByDriverIdDocuments,
  getDriversByDriverIdDocumentsById,
  getDriversByDriverIdDocumentsCompliance,
  patchBusesByBusIdDocumentsById,
  patchDriversByDriverIdDocumentsById,
  postBusesByBusIdDocuments,
  postDriversByDriverIdDocuments,
  putDocumentrequirements,
} from '../../src/server/api/documents';
import {
  getEmergencies,
  getEmergenciesActive,
  getEmergenciesById,
  getEmergenciesMine,
  patchEmergenciesByIdCancel,
  patchEmergenciesByIdStatus,
  postEmergenciesSos,
} from '../../src/server/api/emergencies';
import {
  getTripsByTripIdArrivals,
  getTripsByTripIdEta,
  getTripsByTripIdProgress,
} from '../../src/server/api/eta';
import {
  getHealth,
  getHealthReady,
} from '../../src/server/api/health';
import {
  getTripsByTripIdLocation,
  getTripsByTripIdLocationHistory,
} from '../../src/server/api/live-tracking';
import {
  deleteNotificationsDevicesByToken,
  getParentNotifications,
  patchParentNotificationsByIdRead,
  patchParentNotificationsReadall,
  postNotificationsDevices,
} from '../../src/server/api/notifications';
import {
  getParentChildren,
  getParentChildrenById,
  getParentChildrenByIdToday,
  getParentChildrenByIdTracking,
  getParentDashboard,
} from '../../src/server/api/parent-portal';
import {
  deleteParentsById,
  deleteParentsByParentIdStudentsByStudentId,
  deleteStudentsByStudentIdGuardiansByParentId,
  getParents,
  getParentsById,
  getParentsByParentIdStudents,
  getParentsMeStudents,
  getStudentsByStudentIdGuardians,
  patchParentsById,
  patchParentsByParentIdStudentsByStudentId,
  patchStudentsByStudentIdGuardiansByParentId,
  postParents,
  postParentsByParentIdStudents,
  postStudentsByStudentIdGuardians,
} from '../../src/server/api/parents';
import {
  getReports,
  getReportsByReport,
  getReportsByReportExport,
  getReportsOverview,
} from '../../src/server/api/reports';
import {
  deleteRoutesById,
  getRoutes,
  getRoutesById,
  getRoutesByIdDetails,
  getRoutesByIdStops,
  patchRoutesById,
  postRoutes,
  putRoutesByIdStops,
} from '../../src/server/api/routes';
import {
  postSchools,
} from '../../src/server/api/schools';
import {
  deleteConductorsById,
  deleteDriversById,
  getConductors,
  getConductorsById,
  getDrivers,
  getDriversById,
  patchConductorsById,
  patchDriversById,
  postConductors,
  postDrivers,
} from '../../src/server/api/staff';
import {
  deleteStopsById,
  getStops,
  getStopsById,
  patchStopsById,
  postStops,
} from '../../src/server/api/stops';
import {
  deleteStudentsById,
  getStudents,
  getStudentsById,
  patchStudentsById,
  postStudents,
} from '../../src/server/api/students';
import {
  getTripsByTripIdStudents,
  getTripsByTripIdStudentsByStudentId,
  postTripsByTripIdStudentsByStudentIdBoard,
  postTripsByTripIdStudentsByStudentIdDrop,
} from '../../src/server/api/trip-attendance';
import {
  deleteTripsById,
  getTrips,
  getTripsById,
  patchTripsById,
  patchTripsByIdStatus,
  postTrips,
  postTripsByIdCancel,
} from '../../src/server/api/trips';

/**
 * Every endpoint of the API, mounted the way the `route.ts` files under
 * `src/app/api/v1` mount it. Generated from the endpoint definitions.
 */
export const ALL_ROUTES: TestRoute[] = [
  { method: 'GET', path: '/admin/dashboard', definition: getAdminDashboard },
  { method: 'GET', path: '/admin/plans', definition: getAdminPlans },
  { method: 'POST', path: '/admin/plans', definition: postAdminPlans },
  { method: 'GET', path: '/admin/plans/:id', definition: getAdminPlansById },
  { method: 'PATCH', path: '/admin/plans/:id', definition: patchAdminPlansById },
  { method: 'POST', path: '/admin/plans/:id/activate', definition: postAdminPlansByIdActivate },
  { method: 'POST', path: '/admin/plans/:id/deactivate', definition: postAdminPlansByIdDeactivate },
  { method: 'GET', path: '/admin/schools', definition: getAdminSchools },
  { method: 'POST', path: '/admin/schools', definition: postAdminSchools },
  { method: 'GET', path: '/admin/schools/:schoolId', definition: getAdminSchoolsById },
  { method: 'PATCH', path: '/admin/schools/:schoolId', definition: patchAdminSchoolsById },
  { method: 'POST', path: '/admin/schools/:schoolId/activate', definition: postAdminSchoolsByIdActivate },
  { method: 'GET', path: '/admin/schools/:schoolId/admins', definition: getAdminSchoolsByIdAdmins },
  { method: 'POST', path: '/admin/schools/:schoolId/admins', definition: postAdminSchoolsByIdAdmins },
  { method: 'PATCH', path: '/admin/schools/:schoolId/admins/:adminId', definition: patchAdminSchoolsByIdAdminsByAdminId },
  { method: 'POST', path: '/admin/schools/:schoolId/admins/:adminId/activate', definition: postAdminSchoolsByIdAdminsByAdminIdActivate },
  { method: 'POST', path: '/admin/schools/:schoolId/admins/:adminId/deactivate', definition: postAdminSchoolsByIdAdminsByAdminIdDeactivate },
  { method: 'POST', path: '/admin/schools/:schoolId/admins/:adminId/reset-password', definition: postAdminSchoolsByIdAdminsByAdminIdResetpassword },
  { method: 'POST', path: '/admin/schools/:schoolId/deactivate', definition: postAdminSchoolsByIdDeactivate },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/buses', definition: getAdminSchoolsBySchoolIdManageBuses },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/buses', definition: postAdminSchoolsBySchoolIdManageBuses },
  { method: 'DELETE', path: '/admin/schools/:schoolId/manage/buses/:busId', definition: deleteAdminSchoolsBySchoolIdManageBusesById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/buses/:busId', definition: getAdminSchoolsBySchoolIdManageBusesById },
  { method: 'PATCH', path: '/admin/schools/:schoolId/manage/buses/:busId', definition: patchAdminSchoolsBySchoolIdManageBusesById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/conductors', definition: getAdminSchoolsBySchoolIdManageConductors },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/conductors', definition: postAdminSchoolsBySchoolIdManageConductors },
  { method: 'DELETE', path: '/admin/schools/:schoolId/manage/conductors/:id', definition: deleteAdminSchoolsBySchoolIdManageConductorsById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/conductors/:id', definition: getAdminSchoolsBySchoolIdManageConductorsById },
  { method: 'PATCH', path: '/admin/schools/:schoolId/manage/conductors/:id', definition: patchAdminSchoolsBySchoolIdManageConductorsById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/drivers', definition: getAdminSchoolsBySchoolIdManageDrivers },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/drivers', definition: postAdminSchoolsBySchoolIdManageDrivers },
  { method: 'DELETE', path: '/admin/schools/:schoolId/manage/drivers/:driverId', definition: deleteAdminSchoolsBySchoolIdManageDriversById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/drivers/:driverId', definition: getAdminSchoolsBySchoolIdManageDriversById },
  { method: 'PATCH', path: '/admin/schools/:schoolId/manage/drivers/:driverId', definition: patchAdminSchoolsBySchoolIdManageDriversById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/exports', definition: getAdminSchoolsBySchoolIdManageExports },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/exports/:dataset', definition: getAdminSchoolsBySchoolIdManageExportsByDataset },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/imports/:module/commit', definition: postAdminSchoolsBySchoolIdManageImportsByModuleCommit },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/imports/:module/template', definition: getAdminSchoolsBySchoolIdManageImportsByModuleTemplate },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/imports/:module/validate', definition: postAdminSchoolsBySchoolIdManageImportsByModuleValidate },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/imports/history', definition: getAdminSchoolsBySchoolIdManageImportsHistory },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/imports/history/:id', definition: getAdminSchoolsBySchoolIdManageImportsHistoryById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/imports/history/:id/error-file', definition: getAdminSchoolsBySchoolIdManageImportsHistoryByIdErrorfile },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/imports/modules', definition: getAdminSchoolsBySchoolIdManageImportsModules },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/parents', definition: getAdminSchoolsBySchoolIdManageParents },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/parents', definition: postAdminSchoolsBySchoolIdManageParents },
  { method: 'DELETE', path: '/admin/schools/:schoolId/manage/parents/:parentId', definition: deleteAdminSchoolsBySchoolIdManageParentsByParentId },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/parents/:parentId', definition: getAdminSchoolsBySchoolIdManageParentsByParentId },
  { method: 'PATCH', path: '/admin/schools/:schoolId/manage/parents/:parentId', definition: patchAdminSchoolsBySchoolIdManageParentsByParentId },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/parents/:parentId/students', definition: getAdminSchoolsBySchoolIdManageParentsByParentIdStudents },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/parents/:parentId/students', definition: postAdminSchoolsBySchoolIdManageParentsByParentIdStudents },
  { method: 'DELETE', path: '/admin/schools/:schoolId/manage/parents/:parentId/students/:studentId', definition: deleteAdminSchoolsBySchoolIdManageParentsByParentIdStudentsByStudentId },
  { method: 'PATCH', path: '/admin/schools/:schoolId/manage/parents/:parentId/students/:studentId', definition: patchAdminSchoolsBySchoolIdManageParentsByParentIdStudentsByStudentId },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/reports', definition: getAdminSchoolsBySchoolIdManageReports },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/reports/:report', definition: getAdminSchoolsBySchoolIdManageReportsByReport },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/reports/:report/export', definition: getAdminSchoolsBySchoolIdManageReportsByReportExport },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/reports/overview', definition: getAdminSchoolsBySchoolIdManageReportsOverview },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/route-assignments', definition: getAdminSchoolsBySchoolIdManageRouteassignments },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/route-assignments', definition: postAdminSchoolsBySchoolIdManageRouteassignments },
  { method: 'DELETE', path: '/admin/schools/:schoolId/manage/route-assignments/:id', definition: deleteAdminSchoolsBySchoolIdManageRouteassignmentsById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/route-assignments/:id', definition: getAdminSchoolsBySchoolIdManageRouteassignmentsById },
  { method: 'PATCH', path: '/admin/schools/:schoolId/manage/route-assignments/:id', definition: patchAdminSchoolsBySchoolIdManageRouteassignmentsById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/routes', definition: getAdminSchoolsBySchoolIdManageRoutes },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/routes', definition: postAdminSchoolsBySchoolIdManageRoutes },
  { method: 'DELETE', path: '/admin/schools/:schoolId/manage/routes/:id', definition: deleteAdminSchoolsBySchoolIdManageRoutesById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/routes/:id', definition: getAdminSchoolsBySchoolIdManageRoutesById },
  { method: 'PATCH', path: '/admin/schools/:schoolId/manage/routes/:id', definition: patchAdminSchoolsBySchoolIdManageRoutesById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/routes/:id/details', definition: getAdminSchoolsBySchoolIdManageRoutesByIdDetails },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/routes/:id/stops', definition: getAdminSchoolsBySchoolIdManageRoutesByIdStops },
  { method: 'PUT', path: '/admin/schools/:schoolId/manage/routes/:id/stops', definition: putAdminSchoolsBySchoolIdManageRoutesByIdStops },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/session', definition: postAdminSchoolsBySchoolIdManageSession },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/session/current', definition: getAdminSchoolsBySchoolIdManageSessionCurrent },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/session/end', definition: postAdminSchoolsBySchoolIdManageSessionEnd },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/stops', definition: getAdminSchoolsBySchoolIdManageStops },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/stops', definition: postAdminSchoolsBySchoolIdManageStops },
  { method: 'DELETE', path: '/admin/schools/:schoolId/manage/stops/:id', definition: deleteAdminSchoolsBySchoolIdManageStopsById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/stops/:id', definition: getAdminSchoolsBySchoolIdManageStopsById },
  { method: 'PATCH', path: '/admin/schools/:schoolId/manage/stops/:id', definition: patchAdminSchoolsBySchoolIdManageStopsById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/students', definition: getAdminSchoolsBySchoolIdManageStudents },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/students', definition: postAdminSchoolsBySchoolIdManageStudents },
  { method: 'DELETE', path: '/admin/schools/:schoolId/manage/students/:studentId', definition: deleteAdminSchoolsBySchoolIdManageStudentsById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/students/:studentId', definition: getAdminSchoolsBySchoolIdManageStudentsById },
  { method: 'PATCH', path: '/admin/schools/:schoolId/manage/students/:studentId', definition: patchAdminSchoolsBySchoolIdManageStudentsById },
  { method: 'GET', path: '/admin/schools/:schoolId/manage/students/:studentId/guardians', definition: getAdminSchoolsBySchoolIdManageStudentsByStudentIdGuardians },
  { method: 'POST', path: '/admin/schools/:schoolId/manage/students/:studentId/guardians', definition: postAdminSchoolsBySchoolIdManageStudentsByStudentIdGuardians },
  { method: 'DELETE', path: '/admin/schools/:schoolId/manage/students/:studentId/guardians/:parentId', definition: deleteAdminSchoolsBySchoolIdManageStudentsByStudentIdGuardiansByParentId },
  { method: 'PATCH', path: '/admin/schools/:schoolId/manage/students/:studentId/guardians/:parentId', definition: patchAdminSchoolsBySchoolIdManageStudentsByStudentIdGuardiansByParentId },
  { method: 'GET', path: '/admin/schools/:schoolId/subscription', definition: getAdminSchoolsBySchoolIdSubscription },
  { method: 'PATCH', path: '/admin/schools/:schoolId/subscription', definition: patchAdminSchoolsBySchoolIdSubscription },
  { method: 'POST', path: '/admin/schools/:schoolId/subscription', definition: postAdminSchoolsBySchoolIdSubscription },
  { method: 'POST', path: '/admin/schools/:schoolId/subscription/cancel', definition: postAdminSchoolsBySchoolIdSubscriptionCancel },
  { method: 'GET', path: '/admin/schools/:schoolId/subscription/history', definition: getAdminSchoolsBySchoolIdSubscriptionHistory },
  { method: 'GET', path: '/admin/subscriptions', definition: getAdminSubscriptions },
  { method: 'GET', path: '/assignments', definition: getAssignments },
  { method: 'POST', path: '/assignments', definition: postAssignments },
  { method: 'DELETE', path: '/assignments/:id', definition: deleteAssignmentsById },
  { method: 'GET', path: '/assignments/:id', definition: getAssignmentsById },
  { method: 'PATCH', path: '/assignments/:id', definition: patchAssignmentsById },
  { method: 'GET', path: '/audit-logs', definition: getAuditlogs },
  { method: 'GET', path: '/auth-test/admin-only', definition: getAuthtestAdminonly },
  { method: 'GET', path: '/auth-test/me', definition: getAuthtestMe },
  { method: 'GET', path: '/auth-test/staff-only', definition: getAuthtestStaffonly },
  { method: 'GET', path: '/auth/csrf', definition: getAuthCsrf },
  { method: 'POST', path: '/auth/login', definition: postAuthLogin },
  { method: 'POST', path: '/auth/logout', definition: postAuthLogout },
  { method: 'POST', path: '/auth/refresh', definition: postAuthRefresh },
  { method: 'GET', path: '/buses', definition: getBuses },
  { method: 'POST', path: '/buses', definition: postBuses },
  { method: 'DELETE', path: '/buses/:busId', definition: deleteBusesById },
  { method: 'GET', path: '/buses/:busId', definition: getBusesById },
  { method: 'PATCH', path: '/buses/:busId', definition: patchBusesById },
  { method: 'GET', path: '/buses/:busId/documents', definition: getBusesByBusIdDocuments },
  { method: 'POST', path: '/buses/:busId/documents', definition: postBusesByBusIdDocuments },
  { method: 'DELETE', path: '/buses/:busId/documents/:id', definition: deleteBusesByBusIdDocumentsById },
  { method: 'GET', path: '/buses/:busId/documents/:id', definition: getBusesByBusIdDocumentsById },
  { method: 'PATCH', path: '/buses/:busId/documents/:id', definition: patchBusesByBusIdDocumentsById },
  { method: 'GET', path: '/buses/:busId/documents/compliance', definition: getBusesByBusIdDocumentsCompliance },
  { method: 'GET', path: '/conductors', definition: getConductors },
  { method: 'POST', path: '/conductors', definition: postConductors },
  { method: 'DELETE', path: '/conductors/:id', definition: deleteConductorsById },
  { method: 'GET', path: '/conductors/:id', definition: getConductorsById },
  { method: 'PATCH', path: '/conductors/:id', definition: patchConductorsById },
  { method: 'GET', path: '/document-requirements', definition: getDocumentrequirements },
  { method: 'PUT', path: '/document-requirements', definition: putDocumentrequirements },
  { method: 'GET', path: '/documents/overview', definition: getDocumentsOverview },
  { method: 'GET', path: '/drivers', definition: getDrivers },
  { method: 'POST', path: '/drivers', definition: postDrivers },
  { method: 'DELETE', path: '/drivers/:driverId', definition: deleteDriversById },
  { method: 'GET', path: '/drivers/:driverId', definition: getDriversById },
  { method: 'PATCH', path: '/drivers/:driverId', definition: patchDriversById },
  { method: 'GET', path: '/drivers/:driverId/documents', definition: getDriversByDriverIdDocuments },
  { method: 'POST', path: '/drivers/:driverId/documents', definition: postDriversByDriverIdDocuments },
  { method: 'DELETE', path: '/drivers/:driverId/documents/:id', definition: deleteDriversByDriverIdDocumentsById },
  { method: 'GET', path: '/drivers/:driverId/documents/:id', definition: getDriversByDriverIdDocumentsById },
  { method: 'PATCH', path: '/drivers/:driverId/documents/:id', definition: patchDriversByDriverIdDocumentsById },
  { method: 'GET', path: '/drivers/:driverId/documents/compliance', definition: getDriversByDriverIdDocumentsCompliance },
  { method: 'GET', path: '/emergencies', definition: getEmergencies },
  { method: 'GET', path: '/emergencies/:id', definition: getEmergenciesById },
  { method: 'PATCH', path: '/emergencies/:id/cancel', definition: patchEmergenciesByIdCancel },
  { method: 'PATCH', path: '/emergencies/:id/status', definition: patchEmergenciesByIdStatus },
  { method: 'GET', path: '/emergencies/active', definition: getEmergenciesActive },
  { method: 'GET', path: '/emergencies/mine', definition: getEmergenciesMine },
  { method: 'POST', path: '/emergencies/sos', definition: postEmergenciesSos },
  { method: 'GET', path: '/exports', definition: getExports },
  { method: 'GET', path: '/exports/:dataset', definition: getExportsByDataset },
  { method: 'GET', path: '/health', definition: getHealth },
  { method: 'GET', path: '/health/ready', definition: getHealthReady },
  { method: 'POST', path: '/imports/:module/commit', definition: postImportsByModuleCommit },
  { method: 'GET', path: '/imports/:module/template', definition: getImportsByModuleTemplate },
  { method: 'POST', path: '/imports/:module/validate', definition: postImportsByModuleValidate },
  { method: 'GET', path: '/imports/history', definition: getImportsHistory },
  { method: 'GET', path: '/imports/history/:id', definition: getImportsHistoryById },
  { method: 'GET', path: '/imports/history/:id/error-file', definition: getImportsHistoryByIdErrorfile },
  { method: 'GET', path: '/imports/modules', definition: getImportsModules },
  { method: 'POST', path: '/notifications/devices', definition: postNotificationsDevices },
  { method: 'DELETE', path: '/notifications/devices/:token', definition: deleteNotificationsDevicesByToken },
  { method: 'GET', path: '/parent/children', definition: getParentChildren },
  { method: 'GET', path: '/parent/children/:id', definition: getParentChildrenById },
  { method: 'GET', path: '/parent/children/:id/today', definition: getParentChildrenByIdToday },
  { method: 'GET', path: '/parent/children/:id/tracking', definition: getParentChildrenByIdTracking },
  { method: 'GET', path: '/parent/dashboard', definition: getParentDashboard },
  { method: 'GET', path: '/parent/notifications', definition: getParentNotifications },
  { method: 'PATCH', path: '/parent/notifications/:id/read', definition: patchParentNotificationsByIdRead },
  { method: 'PATCH', path: '/parent/notifications/read-all', definition: patchParentNotificationsReadall },
  { method: 'GET', path: '/parents', definition: getParents },
  { method: 'POST', path: '/parents', definition: postParents },
  { method: 'DELETE', path: '/parents/:parentId', definition: deleteParentsById },
  { method: 'GET', path: '/parents/:parentId', definition: getParentsById },
  { method: 'PATCH', path: '/parents/:parentId', definition: patchParentsById },
  { method: 'GET', path: '/parents/:parentId/students', definition: getParentsByParentIdStudents },
  { method: 'POST', path: '/parents/:parentId/students', definition: postParentsByParentIdStudents },
  { method: 'DELETE', path: '/parents/:parentId/students/:studentId', definition: deleteParentsByParentIdStudentsByStudentId },
  { method: 'PATCH', path: '/parents/:parentId/students/:studentId', definition: patchParentsByParentIdStudentsByStudentId },
  { method: 'GET', path: '/parents/me/students', definition: getParentsMeStudents },
  { method: 'GET', path: '/reports', definition: getReports },
  { method: 'GET', path: '/reports/:report', definition: getReportsByReport },
  { method: 'GET', path: '/reports/:report/export', definition: getReportsByReportExport },
  { method: 'GET', path: '/reports/overview', definition: getReportsOverview },
  { method: 'GET', path: '/route-assignments', definition: getRouteassignments },
  { method: 'POST', path: '/route-assignments', definition: postRouteassignments },
  { method: 'DELETE', path: '/route-assignments/:id', definition: deleteRouteassignmentsById },
  { method: 'GET', path: '/route-assignments/:id', definition: getRouteassignmentsById },
  { method: 'PATCH', path: '/route-assignments/:id', definition: patchRouteassignmentsById },
  { method: 'GET', path: '/routes', definition: getRoutes },
  { method: 'POST', path: '/routes', definition: postRoutes },
  { method: 'DELETE', path: '/routes/:id', definition: deleteRoutesById },
  { method: 'GET', path: '/routes/:id', definition: getRoutesById },
  { method: 'PATCH', path: '/routes/:id', definition: patchRoutesById },
  { method: 'GET', path: '/routes/:id/details', definition: getRoutesByIdDetails },
  { method: 'GET', path: '/routes/:id/stops', definition: getRoutesByIdStops },
  { method: 'PUT', path: '/routes/:id/stops', definition: putRoutesByIdStops },
  { method: 'POST', path: '/schools', definition: postSchools },
  { method: 'GET', path: '/stops', definition: getStops },
  { method: 'POST', path: '/stops', definition: postStops },
  { method: 'DELETE', path: '/stops/:id', definition: deleteStopsById },
  { method: 'GET', path: '/stops/:id', definition: getStopsById },
  { method: 'PATCH', path: '/stops/:id', definition: patchStopsById },
  { method: 'GET', path: '/students', definition: getStudents },
  { method: 'POST', path: '/students', definition: postStudents },
  { method: 'DELETE', path: '/students/:studentId', definition: deleteStudentsById },
  { method: 'GET', path: '/students/:studentId', definition: getStudentsById },
  { method: 'PATCH', path: '/students/:studentId', definition: patchStudentsById },
  { method: 'GET', path: '/students/:studentId/guardians', definition: getStudentsByStudentIdGuardians },
  { method: 'POST', path: '/students/:studentId/guardians', definition: postStudentsByStudentIdGuardians },
  { method: 'DELETE', path: '/students/:studentId/guardians/:parentId', definition: deleteStudentsByStudentIdGuardiansByParentId },
  { method: 'PATCH', path: '/students/:studentId/guardians/:parentId', definition: patchStudentsByStudentIdGuardiansByParentId },
  { method: 'GET', path: '/trips', definition: getTrips },
  { method: 'POST', path: '/trips', definition: postTrips },
  { method: 'DELETE', path: '/trips/:tripId', definition: deleteTripsById },
  { method: 'GET', path: '/trips/:tripId', definition: getTripsById },
  { method: 'PATCH', path: '/trips/:tripId', definition: patchTripsById },
  { method: 'GET', path: '/trips/:tripId/arrivals', definition: getTripsByTripIdArrivals },
  { method: 'POST', path: '/trips/:tripId/cancel', definition: postTripsByIdCancel },
  { method: 'GET', path: '/trips/:tripId/eta', definition: getTripsByTripIdEta },
  { method: 'GET', path: '/trips/:tripId/location', definition: getTripsByTripIdLocation },
  { method: 'GET', path: '/trips/:tripId/location/history', definition: getTripsByTripIdLocationHistory },
  { method: 'GET', path: '/trips/:tripId/progress', definition: getTripsByTripIdProgress },
  { method: 'PATCH', path: '/trips/:tripId/status', definition: patchTripsByIdStatus },
  { method: 'GET', path: '/trips/:tripId/students', definition: getTripsByTripIdStudents },
  { method: 'GET', path: '/trips/:tripId/students/:studentId', definition: getTripsByTripIdStudentsByStudentId },
  { method: 'POST', path: '/trips/:tripId/students/:studentId/board', definition: postTripsByTripIdStudentsByStudentIdBoard },
  { method: 'POST', path: '/trips/:tripId/students/:studentId/drop', definition: postTripsByTripIdStudentsByStudentIdDrop },
];
