/**
 * Every id in the API is a UUID v4 (generated by the backend). Route params
 * that arrive without a value — e.g. when a dynamic detail route such as
 * `trips/[id]` is opened directly instead of being pushed with a real id —
 * must never reach the API: an empty `:id` can silently match a *sibling*
 * list route (e.g. `GET /parent/children/` → the children list) whose payload
 * has a different shape and crashes screens that expect a single record.
 */

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Is `value` a well-formed UUID — the format of every API resource id? */
export function isUuid(value: string | null | undefined): boolean {
  return typeof value === 'string' ? UUID_PATTERN.test(value.trim()) : false;
}

/** Friendly message for detail screens opened without a usable id. */
export function invalidIdMessage(what: string): string {
  return `This ${what} could not be opened — the link is missing a valid id. Go back and open it again from the list.`;
}
