export const PLAN_LIMITS_SUBSCRIPTIONS_REPOSITORY = 'PLAN_LIMITS_SUBSCRIPTIONS_REPOSITORY';
export const PLAN_LIMITS_PLANS_REPOSITORY = 'PLAN_LIMITS_PLANS_REPOSITORY';
export const PLAN_LIMITS_STUDENTS_REPOSITORY = 'PLAN_LIMITS_STUDENTS_REPOSITORY';
export const PLAN_LIMITS_BUSES_REPOSITORY = 'PLAN_LIMITS_BUSES_REPOSITORY';
export const PLAN_LIMITS_ROUTES_REPOSITORY = 'PLAN_LIMITS_ROUTES_REPOSITORY';
export const PLAN_LIMITS_STOPS_REPOSITORY = 'PLAN_LIMITS_STOPS_REPOSITORY';
export const PLAN_LIMITS_USERS_REPOSITORY = 'PLAN_LIMITS_USERS_REPOSITORY';
export const PLAN_LIMITS_TRIPS_REPOSITORY = 'PLAN_LIMITS_TRIPS_REPOSITORY';
