export {
  CreateMarketingTemplateDto,
  UpdateMarketingTemplateDto,
  SaveMarketingTemplateContentDto,
  MarketingTemplateRenderDto,
  ListMarketingTemplatesQueryDto,
  CreateMarketingCampaignDto,
  UpdateMarketingCampaignDto,
  ScheduleMarketingCampaignDto,
  MarketingAudiencePreviewDto,
  ListMarketingCampaignsQueryDto,
  PublicDemoRequestDto,
  ListMarketingLeadsQueryDto,
  UpdateMarketingLeadStatusDto,
  AddMarketingLeadNoteDto,
} from './marketing.dto';
