export {
  CreateMarketingTemplateDto,
  UpdateMarketingTemplateDto,
  SaveMarketingTemplateContentDto,
  MarketingTemplateRenderDto,
  ListMarketingTemplatesQueryDto,
  CreateMarketingCampaignDto,
  UpdateMarketingCampaignDto,
  ScheduleMarketingCampaignDto,
  MarketingAudiencePreviewDto,
  ListMarketingCampaignsQueryDto,
  PublicDemoRequestDto,
  ListMarketingLeadsQueryDto,
  UpdateMarketingLeadStatusDto,
  AddMarketingLeadNoteDto,
  UpdateMarketingDeliverySettingsDto,
  ListMarketingSuppressionsQueryDto,
  CreateMarketingSuppressionDto,
  DeleteMarketingSuppressionDto,
  EraseMarketingLeadDto,
} from './marketing.dto';
